# Generated by Django 4.0.2 on 2022-03-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='floors',
            field=models.ManyToManyField(through='user.BuildingFloor', to='user.Floor'),
        ),
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='buildingfloor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='floor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wholesaler',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
