# Generated by Django 4.0.2 on 2022-03-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_building_floors_alter_building_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['id']},
        ),
    ]
