# Generated by Django 4.0.2 on 2022-04-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_membership_discount_rate_membership_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
