# Generated by Django 3.2.8 on 2021-12-13 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_update_password',
            field=models.DateField(default=datetime.datetime(2021, 12, 13, 7, 10, 21, 243694, tzinfo=utc)),
        ),
    ]
