# Generated by Django 3.2.8 on 2021-12-13 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_last_update_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_update_password',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 7, 11, 5, 825921, tzinfo=utc)),
        ),
    ]
