# Generated by Django 4.0.2 on 2022-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_like_shoppers'),
        ('user', '0004_productlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='like_products',
            field=models.ManyToManyField(through='user.ProductLike', to='product.Product'),
        ),
    ]
