# Generated by Django 4.0.2 on 2022-04-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_shopper_like_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppershippingaddress',
            old_name='mobile_number',
            new_name='reciever_mobile_number',
        ),
        migrations.RenameField(
            model_name='shoppershippingaddress',
            old_name='receiver_name',
            new_name='reciever_name',
        ),
        migrations.RenameField(
            model_name='shoppershippingaddress',
            old_name='phone_number',
            new_name='reciever_phone_number',
        ),
    ]
