# Generated by Django 3.2.8 on 2021-12-14 06:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_last_update_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_update_password',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 6, 6, 9, 5623, tzinfo=utc)),
        ),
    ]
