# Generated by Django 3.2.8 on 2021-12-15 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_last_update_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_update_password',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
