# Generated by Django 4.0.2 on 2022-04-13 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_mobile_number_shoppershippingaddress_reciever_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppershippingaddress',
            name='shopper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='user.shopper'),
        ),
    ]
