# Generated by Django 4.0.2 on 2022-04-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_shoppershippingaddress_shopper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppershippingaddress',
            old_name='reciever_mobile_number',
            new_name='receiver_mobile_number',
        ),
        migrations.RenameField(
            model_name='shoppershippingaddress',
            old_name='reciever_name',
            new_name='receiver_name',
        ),
        migrations.RenameField(
            model_name='shoppershippingaddress',
            old_name='reciever_phone_number',
            new_name='receiver_phone_number',
        ),
    ]
