# Generated by Django 4.0.2 on 2022-04-22 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_statushistory_delete_statuslog'),
        ('user', '0008_rename_reciever_mobile_number_shoppershippingaddress_receiver_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('point', models.IntegerField()),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.orderitem')),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.shopper')),
            ],
            options={
                'db_table': 'point_history',
            },
        ),
    ]
