# Generated by Django 4.0.2 on 2022-04-24 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_statushistory_delete_statuslog'),
        ('user', '0009_pointhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointhistory',
            name='order_item',
        ),
        migrations.AddField(
            model_name='pointhistory',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.order'),
        ),
    ]
