# Generated by Django 4.0.2 on 2022-04-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_pointhistory_order_item_pointhistory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointhistory',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
