# Generated by Django 4.0.2 on 2022-04-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_pointhistory_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointhistory',
            options={'ordering': ['id']},
        ),
    ]
