# Generated by Django 4.0.2 on 2022-05-31 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_pointhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointhistory',
            options={'ordering': ['-id']},
        ),
    ]
