# Generated by Django 4.0.2 on 2022-05-26 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_delete_cart'),
        ('user', '0013_alter_pointhistory_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carts', to='product.option')),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carts', to='user.shopper')),
            ],
            options={
                'db_table': 'cart',
                'ordering': ['-created_at'],
            },
        ),
    ]
