# Generated by Django 4.0.2 on 2022-05-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_delete_cart'),
        ('user', '0014_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('shopper', 'option')},
        ),
    ]
