# Generated by Django 4.0.2 on 2022-06-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_pointhistory_options'),
        ('user', '0015_alter_cart_unique_together'),
    ]

    operations = [
    ]
