# Generated by Django 4.0.2 on 2022-06-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_shoppercoupon_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppercoupon',
            name='is_available',
            field=models.IntegerField(default=True),
        ),
    ]
