# Generated by Django 4.0.2 on 2022-06-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_rename_coupon_classification_coupon_classification'),
        ('user', '0020_shopper_coupons_alter_shoppercoupon_coupon_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppercoupon',
            unique_together={('shopper', 'coupon')},
        ),
    ]
