# Generated by Django 4.0.2 on 2022-06-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_shoppercoupon_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppercoupon',
            options={'ordering': ['-coupon']},
        ),
    ]
