# Generated by Django 4.0.2 on 2022-06-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_shoppercoupon_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppercoupon',
            options={},
        ),
    ]
