# Generated by Django 4.0.2 on 2022-06-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_shoppercoupon_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
