# Generated by Django 4.0.2 on 2022-07-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_membership_discount_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppercoupon',
            name='is_available',
        ),
        migrations.AddField(
            model_name='shoppercoupon',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
