# Generated by Django 4.0.2 on 2022-07-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_remove_shoppercoupon_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='discount_rate',
            field=models.IntegerField(),
        ),
    ]
