# Generated by Django 4.0.2 on 2022-06-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0025_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('discount_rate', models.IntegerField(null=True)),
                ('discount_price', models.IntegerField(null=True)),
                ('minimum_order_price', models.IntegerField(default=0)),
                ('maximum_order_price', models.IntegerField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('available_period', models.IntegerField(null=True)),
                ('is_auto_issue', models.BooleanField()),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='CouponClassification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'coupon_classification',
            },
        ),
        migrations.CreateModel(
            name='CouponSubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coupon.coupon')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.subcategory')),
            ],
            options={
                'db_table': 'coupon_sub_category',
            },
        ),
        migrations.CreateModel(
            name='CouponProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coupon.coupon')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
            options={
                'db_table': 'coupon_product',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coupon.couponclassification'),
        ),
    ]
