# Generated by Django 4.0.2 on 2022-06-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='maximum_order_price',
            new_name='maximum_discount_price',
        ),
        migrations.AlterField(
            model_name='couponclassification',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
