# Generated by Django 4.0.2 on 2022-06-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_rename_coupon_classification_coupon_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponsubcategory',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='couponsubcategory',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='CouponProduct',
        ),
        migrations.DeleteModel(
            name='CouponSubCategory',
        ),
    ]
