# Generated by Django 4.0.2 on 2022-06-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_delete_cart'),
        ('coupon', '0004_remove_couponsubcategory_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(to='product.Product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='sub_categories',
            field=models.ManyToManyField(to='product.SubCategory'),
        ),
    ]
