# Generated by Django 4.0.2 on 2022-06-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_delete_cart'),
        ('coupon', '0005_coupon_products_coupon_sub_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(db_table='coupon_product', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='sub_categories',
            field=models.ManyToManyField(db_table='coupon_sub_category', to='product.SubCategory'),
        ),
    ]
