# Generated by Django 4.0.2 on 2022-07-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0012_alter_couponclassification_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='minimum_order_price',
            new_name='minimum_product_price',
        ),
    ]
