# Generated by Django 4.0.2 on 2022-04-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryImage',
            fields=[
                ('image_url', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'temporary_image',
            },
        ),
    ]
