# Generated by Django 4.0.2 on 2022-07-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_settinggroup_settingitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settinggroup',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='settingitem',
            options={'ordering': ['id']},
        ),
    ]
