# Generated by Django 4.0.2 on 2022-07-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_settinggroup_options_alter_settingitem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingitem',
            old_name='name',
            new_name='value',
        ),
        migrations.AddField(
            model_name='settinggroup',
            name='classification',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='settingitem',
            unique_together={('group', 'value')},
        ),
    ]
