# Generated by Django 4.0.2 on 2022-07-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_name_settingitem_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settinggroup',
            name='classification',
        ),
        migrations.AddField(
            model_name='settinggroup',
            name='key',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
