# Generated by Django 4.0.2 on 2022-07-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_settinggroup_classification_settinggroup_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinggroup',
            name='app',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='settinggroup',
            name='key',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='settinggroup',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='settingitem',
            name='value',
            field=models.CharField(max_length=30),
        ),
    ]
