# Generated by Django 4.0.2 on 2022-07-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_settinggroup_app_alter_settinggroup_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingitem',
            old_name='value',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='settingitem',
            unique_together={('group', 'name')},
        ),
    ]
