# Generated by Django 4.0.2 on 2022-07-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_rename_value_settingitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settinggroup',
            name='request_key',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
