# Generated by Django 4.0.2 on 2022-07-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_settinggroup_request_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settinggroup',
            old_name='key',
            new_name='main_key',
        ),
        migrations.RenameField(
            model_name='settinggroup',
            old_name='request_key',
            new_name='sub_key',
        ),
    ]
