# Generated by Django 4.0.2 on 2022-04-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_rate',
            new_name='base_discount_rate',
        ),
    ]
