# Generated by Django 4.0 on 2022-02-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='price_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='productimages',
            unique_together={('product', 'sequence')},
        ),
    ]
