# Generated by Django 4.0 on 2021-12-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='LargeCategory',
        ),
        migrations.DeleteModel(
            name='SmallCategory',
        ),
    ]
