# Generated by Django 4.0 on 2021-12-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_delete_category_delete_largecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'large_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmallCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'small_category',
                'managed': False,
            },
        ),
    ]
