# Generated by Django 4.0 on 2022-02-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_option_price_difference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'managed': False},
        ),
    ]
