# Generated by Django 4.0.2 on 2022-04-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_discount_rate_product_base_discount_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesaler_stock_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
