# Generated by Django 4.0 on 2022-03-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_option_unique_together_remove_option_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='display_size_name',
            new_name='size',
        ),
    ]
