# Generated by Django 4.0.2 on 2022-04-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_stock_count_product_wholesaler_stock_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_discounted_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
