# Generated by Django 4.0 on 2022-02-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_subcategorysize_subcategory_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
