# Generated by Django 4.0 on 2021-12-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_category_id', models.IntegerField()),
                ('large_category_name', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=10)),
                ('small_category_id', models.IntegerField()),
                ('small_category_name', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=10)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
    ]
