# Generated by Django 4.0 on 2022-02-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductStyle',
        ),
    ]
