# Generated by Django 4.0.2 on 2022-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_productlike'),
        ('product', '0006_alter_product_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='like_shoppers',
            field=models.ManyToManyField(through='user.ProductLike', to='user.Shopper'),
        ),
    ]
