# Generated by Django 4.0.2 on 2022-04-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_like_shoppers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='price_difference',
        ),
    ]
