# Generated by Django 4.0 on 2022-01-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_subcategory_delete_largecategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
