# Generated by Django 4.0.2 on 2022-04-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_option_price_difference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageForValidation',
            fields=[
                ('image_url', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_image_for_validation',
            },
        ),
    ]
