# Generated by Django 4.0 on 2022-02-18 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_subcategory_main_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'age',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flexibility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'flexibility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAdditionalInformation',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='product.product')),
            ],
            options={
                'db_table': 'product_additional_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeeThrough',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'see_through',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'thickness',
                'managed': False,
            },
        ),
    ]
