# Generated by Django 4.0 on 2022-01-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'category',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
