# Generated by Django 4.0 on 2022-02-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_age_flexibility_productadditionalinformation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='laundryinformation',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='productmaterial',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
