# Generated by Django 4.0 on 2022-01-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_maincategory_delete_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maincategory',
            table='main_category',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='sub_category',
        ),
    ]
