# Generated by Django 4.0.2 on 2022-04-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuestionAnswerClassification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'product_question_answer_classification',
            },
        ),
    ]
