# Generated by Django 4.0 on 2022-01-12 20:14

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_maincategory_table_alter_subcategory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.ImageField(max_length=200, upload_to=common.storage.product_image_path)),
            ],
            options={
                'db_table': 'product_images',
                'managed': False,
            },
        ),
    ]
