# Generated by Django 4.0 on 2022-02-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_color_options_alter_laundryinformation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='require_laundry_information',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='require_product_additional_information',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
