# Generated by Django 4.0 on 2022-01-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_size_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'managed': False, 'ordering': ['sequence']},
        ),
    ]
