# Generated by Django 4.0 on 2022-02-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordNgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'keyword_ngram',
                'managed': False,
            },
        ),
    ]
