# Generated by Django 4.0.2 on 2022-05-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_productquestionanswer_shopper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='created_at',
        ),
    ]
