# Generated by Django 4.0.2 on 2022-05-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productquestionanswerclassification',
            options={'ordering': ['id']},
        ),
    ]
