# Generated by Django 4.0.2 on 2022-05-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_productquestionanswerclassification_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together=set(),
        ),
    ]
