# Generated by Django 4.0.2 on 2022-05-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_productmaterial_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquestionanswer',
            name='answer',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
