# Generated by Django 4.0.2 on 2022-05-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_productquestionanswer_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquestionanswer',
            name='answer_completed',
        ),
    ]
