# Generated by Django 4.0.2 on 2022-05-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
