# Generated by Django 4.0.2 on 2022-07-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_settinggroup_options_alter_settingitem_options'),
        ('product', '0025_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('flexibility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flexibility_products', to='common.settingitem')),
                ('lining', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lining_products', to='common.settingitem')),
                ('see_through', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='see_through_products', to='common.settingitem')),
                ('thickness', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='thickness_products', to='common.settingitem')),
            ],
            options={
                'db_table': 'product2',
            },
        ),
    ]
