# Generated by Django 4.0.2 on 2022-07-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_remove_product_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product2',
            name='flexibility',
        ),
        migrations.RemoveField(
            model_name='product2',
            name='lining',
        ),
        migrations.RemoveField(
            model_name='product2',
            name='see_through',
        ),
        migrations.RemoveField(
            model_name='product2',
            name='thickness',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.DeleteModel(
            name='Product2',
        ),
    ]
