# Generated by Django 4.0.2 on 2022-08-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_maincategory_laundry_information_required_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincategory',
            old_name='laundry_information_required',
            new_name='laundry_informations_required',
        ),
    ]
