# Generated by Django 4.0.2 on 2022-08-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_rename_laundry_information_required_maincategory_laundry_informations_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flexibility',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lining',
        ),
        migrations.RemoveField(
            model_name='product',
            name='see_through',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thickness',
        ),
        migrations.DeleteModel(
            name='Flexibility',
        ),
        migrations.DeleteModel(
            name='SeeThrough',
        ),
        migrations.DeleteModel(
            name='Thickness',
        ),
    ]
