# Generated by Django 4.0.2 on 2022-08-10 16:41

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_remove_product_flexibility_remove_product_lining_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='image_url',
            new_name='default_image_url',
        ),
        migrations.AddField(
            model_name='color',
            name='checked_image_url',
            field=models.ImageField(default='', max_length=200, storage=common.storage.ClientSVGStorage, upload_to=''),
            preserve_default=False,
        ),
    ]
