# Generated by Django 4.0.2 on 2022-08-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_rename_image_url_color_default_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='product_color',
            field=models.IntegerField(),
        ),
    ]
