# Generated by Django 4.0.2 on 2022-08-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_option_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='options', to='product.productcolor'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.IntegerField(),
        ),
    ]
