# Generated by Django 4.0.2 on 2022-08-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_alter_productcolor_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
