# Generated by Django 4.0.2 on 2022-08-14 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_rename_key_settinggroup_main_key_and_more'),
        ('product', '0038_delete_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='laundry_informations',
            field=models.ManyToManyField(through='product.ProductLaundryInformation', to='common.SettingItem'),
        ),
        migrations.AlterField(
            model_name='productlaundryinformation',
            name='laundry_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.settingitem'),
        ),
    ]
