# Generated by Django 4.0.2 on 2022-08-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_alter_product_laundry_informations_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaundryInformation',
        ),
    ]
