# Generated by Django 4.0.2 on 2022-08-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_rename_key_settinggroup_main_key_and_more'),
        ('product', '0040_delete_laundryinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='age',
        ),
        migrations.AddField(
            model_name='product',
            name='target_age_group',
            field=models.ForeignKey(default=139, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_target_age_group', to='common.settingitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='laundry_informations',
            field=models.ManyToManyField(related_name='product_laundry_information', through='product.ProductLaundryInformation', to='common.SettingItem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_style', to='common.settingitem'),
        ),
        migrations.DeleteModel(
            name='Age',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
