# Generated by Django 4.0.2 on 2022-08-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_remove_product_age_product_target_age_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='require_laundry_information',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='require_product_additional_information',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='sizes',
        ),
    ]
