# Generated by Django 4.0.2 on 2022-08-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_rename_key_settinggroup_main_key_and_more'),
        ('product', '0043_delete_subcategorysize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AlterField(
            model_name='option',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='options', to='common.settingitem'),
        ),
    ]
