# Generated by Django 4.0.2 on 2022-03-31 16:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.BigIntegerField(unique=True)),
                ('total_price', models.IntegerField()),
                ('discount_price', models.IntegerField(default=0)),
                ('payment_price', models.IntegerField()),
                ('refund_price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItemStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'order_item_status',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'payment_status',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('receiver_name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=11)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('zip_code', models.CharField(max_length=5)),
                ('base_address', models.CharField(max_length=200)),
                ('detail_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shipping_address',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sale_price', models.IntegerField()),
                ('base_discount_price', models.IntegerField(default=0)),
                ('membership_discount_price', models.IntegerField()),
                ('used_point', models.IntegerField(default=0)),
                ('payment_price', models.IntegerField()),
                ('earned_point', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.option')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.orderitemstatus')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.paymentstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.shippingaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='shopper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.shopper'),
        ),
    ]
