# Generated by Django 4.0.2 on 2022-04-07 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_status_alter_orderitem_status_delete_orderitemstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_status', to='order.status')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_log', to='order.orderitem')),
                ('previous_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous_status', to='order.status')),
            ],
            options={
                'db_table': 'status_log',
            },
        ),
    ]
