# Generated by Django 4.0.2 on 2022-04-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_statuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTransition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('next_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transition_next_status', to='order.status')),
                ('previous_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transition_previous_status', to='order.status')),
            ],
        ),
    ]
