# Generated by Django 4.0.2 on 2022-04-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_statustransition'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='statustransition',
            table='status_transition',
        ),
    ]
