# Generated by Django 4.0.2 on 2022-04-12 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_shippingaddress_shipping_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'refund',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReturnInformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.refund')),
            ],
            options={
                'db_table': 'return_information',
            },
        ),
        migrations.CreateModel(
            name='ExchangeInformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_order_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.orderitem')),
            ],
            options={
                'db_table': 'exchange_information',
            },
        ),
        migrations.CreateModel(
            name='CancellationInformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.refund')),
            ],
            options={
                'db_table': 'cancellation_information',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancellation_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.cancellationinformation'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='exchange_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.exchangeinformation'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.returninformation'),
        ),
    ]
