# Generated by Django 4.0.2 on 2022-04-12 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_refund_orderitem_shipping_fee_returninformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationinformation',
            name='refund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.refund'),
        ),
    ]
