# Generated by Django 4.0.2 on 2022-04-18 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_orderitem_cancellation_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationinformation',
            name='order_item',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='order.orderitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangeinformation',
            name='order_item',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='order.orderitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returninformation',
            name='order_item',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='order.orderitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangeinformation',
            name='new_order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous_order_item_exchange_information', to='order.orderitem'),
        ),
    ]
