# Generated by Django 4.0.2 on 2022-04-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_cancellationinformation_order_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationinformation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='exchangeinformation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='returninformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='cancellationinformation',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='order.orderitem'),
        ),
        migrations.AlterField(
            model_name='exchangeinformation',
            name='new_order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='origin_order_item_exchange_information', to='order.orderitem'),
        ),
        migrations.AlterField(
            model_name='exchangeinformation',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='order.orderitem'),
        ),
        migrations.AlterField(
            model_name='returninformation',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='order.orderitem'),
        ),
    ]
