# Generated by Django 4.0.2 on 2022-04-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_statushistory_delete_statuslog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statushistory',
            options={'ordering': ['id']},
        ),
    ]
