# Generated by Django 4.0.2 on 2022-05-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_cancellationinformation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
    ]
