# Generated by Django 4.0.2 on 2022-05-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_options_alter_orderitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_fee',
        ),
    ]
