# Generated by Django 4.0.2 on 2022-05-15 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_remove_orderitem_shipping_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(max_length=30)),
                ('shipping_fee', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.delivery'),
        ),
    ]
