# Generated by Django 4.0.2 on 2022-05-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_delivery_orderitem_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='flag',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
