# Generated by Django 4.0.2 on 2022-05-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_delivery_flag_alter_order_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='delivery',
            table='delivery',
        ),
    ]
