# Generated by Django 4.0.2 on 2022-05-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_delivery_options_alter_delivery_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={},
        ),
        migrations.AlterModelTable(
            name='delivery',
            table=None,
        ),
    ]
