# Generated by Django 4.0.2 on 2022-05-31 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_delivery_options_alter_delivery_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['id']},
        ),
    ]
