# Generated by Django 4.0.2 on 2022-07-04 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_remove_shoppercoupon_is_available_and_more'),
        ('order', '0026_alter_status_options_alter_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupon_discount_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shopper_coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.shoppercoupon'),
        ),
    ]
